config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  root "pages#index"

  get '/about', to: "pages#about"
  get '/drip_thx', to: "pages#drip_thx"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Facebook::Messenger::Server, at: "bot"
  resources :flow_entries

  post '/typeform', to: "typeform#webhook"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flow_entry.rb
class FlowEntry < ApplicationRecord
	belongs_to :user

	scope :sorted_by_date, -> { order(:created_at )}

	def theorical_state
		if challenge_level.nil? || skill_level.nil?
			"None"
		elsif challenge_level > 2 && skill_level == 2
			"Stimulé"
		elsif challenge_level > 2 && skill_level < 2
			"Anxiété"
		elsif challenge_level == 2 && skill_level < 2
			"Inquiétude"
		elsif challenge_level < 2 && skill_level < 2
			"Apathie"
		elsif challenge_level < 2 && skill_level == 2
			"Ennui"
		elsif challenge_level < 2 && skill_level > 2
			"Relaxation"
		elsif challenge_level == 2 && skill_level > 2
			"Controle"
		elsif challenge_level > 2 && skill_level > 2
			"Flow"
		elsif challenge_level == 2 && skill_level == 2
			"Controle"
		end
	end

	def flow_potential
		attributes_to_count = [
			# 0 to 4 (@TODO to change 1 to 5 when saving in db)
			# "challenge_level",
	  	# "skill_level",
			# 1 to 5
	  	"feeling_competent",
	  	"mentally_absorbed",
	  	"clear_objectives",
	  	"control_situation",
	  	"free_from_ego",
	  	"free_from_time",
	  	"clear_conditions",
	  	"great_experience",
	  	"social_quality"
		]
		tab = []
		n = 0
		attributes_to_count.each do |a|
			j = read_attribute(a)
			next if j.nil?
			n = n + 1
			tab << j
		end
		flow_potential = (tab.sum / n.to_f * 20).to_i
	end

	def energy
		return nil if energy_level.nil?
		energy_level
	end

	def happiness
		return nil if happiness_level.nil?
		happiness_level
	end

	def social
		return nil if social_quality.nil?
		social_quality
	end

	FLOW_ENTRY_ATTRIBUTES = [
		"activity_name",
		"activity_category",
  	"skill_level",
  	"challenge_level",
  	"feeling_competent",
  	"mentally_absorbed",
  	"clear_objectives",
  	"control_situation",
  	"free_from_ego",
  	"free_from_time",
  	"clear_conditions",
  	"great_experience",
  	"is_voluntary",
		"energy_level",
  	"happiness_level",
  	"social_quality"
	]
end

app/models/user.rb
class User < ApplicationRecord
	require "facebook/messenger"

	include Facebook::Messenger

	has_many :flow_entry

	def is_admin?
		role == "admin"
	end

	def start_flow_test
		# Define random new Time
		tableau_intervalles = []
		total = 0
		current_time = Time.now
		begin
			nouveau_temps = (3600 + rand(5400))
			current_time = current_time + nouveau_temps
			total = total + nouveau_temps
			tableau_intervalles << current_time.iso8601
		end until total > 80000

		intervalles = ""
		tableau_intervalles.each do |i|
			intervalles << i
			intervalles << " "
		end

		# Then change user attributes in db
		current_user = self
		current_user.update_attributes(:flow_test_intervals => intervalles, :flow_testing => true)
	end

	def received_test
		send_text(self.psid, "J'ai bien recu tes réponses, merci !")
	end

	def flow_test_bip
		send_text(self.psid, "C'est l'heure de répondre aux questions ! https://alfredcorp.typeform.com/to/hwJrHr?id=#{self.private_id}")
	end

	def send_text(psid, text)
		begin
			Bot.deliver({
				recipient: {"id" => psid},
				message: {
				  text: text
				}
			}, access_token: ENV["ACCESS_TOKEN"])
		rescue
			# If message not delivered (a cause can be that the user blocked Alfred)
			puts "This user cannot receive the message somehow"
			self.update_attribute(:flow_testing, false) if self.flow_testing?
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flow_entries_controller.rb
class FlowEntriesController < ApplicationController
	before_action :set_private_mode, :set_user, :set_flow_entries
	layout "no_container"

	def index
		set_errors
	end

	private

	def set_private_mode
		@private_mode = (params[:private_mode] && params[:private_mode] == "true") ? true : false
	end

	def set_user
		@user = User.find_by(private_id: params[:id])
	end

	def set_flow_entries
		@flow_entries = FlowEntry.where(user: @user)&.order(created_at: :desc)
		@flow_entries_by_day = FlowEntry.where(user: @user)&.order(created_at: :desc).group_by{ |t| t.created_at.to_date }
	end

	def set_errors
		if @user.nil?
			flash[:error] = "Utilisateur non trouvé. As tu utilisé le bon lien ?"
		elsif @flow_entries&.count == 0
			flash[:info] = "Tu as bien lancé le test, maintenant surveille simplement les messages d'Alfred"
		elsif @flow_entries_by_day.count < 2 && @flow_entries&.count < 10
			flash[:info] = "Tu auras acces a la liste apres 10 réponses sur minimum 2 jours (progression : #{(@flow_entries.count / 10.0 * 100).to_i}%)"
		end
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
    render :index
  end

  def drip_thx
  end
  
end

app/controllers/typeform_controller.rb
class TypeformController < ApplicationController

  def webhook
    event = JSON.parse(request.body.read)

    form_response = event["form_response"]
    user_private_id = form_response["hidden"]["id"]
    tested_user = User.find_by(private_id: user_private_id)
    if tested_user.nil?
      render json: {:status => 400, :error => "ID can't be found"} and return
    end
    answers = form_response["answers"]
    flow_entry = FlowEntry.new(user: tested_user)
    i = 0
    answers.each do |answer|
      choice = answer[answer["type"]]
      choice = choice["label"] if answer["type"] == "choice" || answer["type"] == "multiple_choice"
      flow_entry.update_attribute("#{FlowEntry::FLOW_ENTRY_ATTRIBUTES[i]}", choice)
      i = i + 1
    end
    tested_user.received_test

    render json: {:status => 200}
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
  before_action :ensure_is_admin, only: [:index]

  def index
    @users = User.all
  end

  private


  def ensure_is_admin
    (redirect_to root_path, notice: %Q[<a href="/users/index">/users/admin</a> accessible only by an admin]) unless @user && @user.is_admin?
  end

  def set_user
    @user = User.find_by(private_id: params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def bg_for_feelings level
    case level
    when 0
      "black"
    when 1
      "#F7BE81"
    when 2
      "#D8F781"
    when 3
      "#CEECF5"
    when 4
      "#81DAF5"
    when 5
      "#58ACFA"
    else
      "white"
    end
  end

  def bg_for_feelings_ten level
    level /= 2 if level
    case level
    when 0
      "#F78181"
    when 1
      "#F7BE81"
    when 2
      "#D8F781"
    when 3
      "#9FF781"
    when 4
      "#81DAF5"
    when 5
      "#58ACFA"
    else
      "white"
    end
  end

  def bg_for_state state
    case state
    when "Flow"
      "#81DAF5"
    when "Stimulé"
      "#58ACFA"
    when "Controle"
      "#CEECF5"
    when "Relaxation"
      "#9FF781"
    when "Ennui"
      "#CEF6CE"
    when "Apathie"
      "#F2F2F2"
    when "Inquiétude"
      "#D8D8D8"
    when "Anxiété"
      "#A4A4A4"
    else
      "white"
    end
  end

  def bg_for_bool bool
    bool ? "#81DAF5" : "#D8F781"
  end

  def color_potential_flow moy
    case moy
    when 0..20
      "#F2F2F2"
    when 21..40
      "#E6E6E6"
    when 41..60
      "#D8D8D8"
    when 61..80
      "#BDBDBD"
    when 81..100
      "#A4A4A4"
    end
  end

  def potential_to_text moy
    case moy
    when 0..20
      "Tres faible"
    when 21..40
      "Faible"
    when 41..60
      "Neutre"
    when 61..80
      "Fort"
    when 81..100
      "Tres fort"
    end
  end
end

app/views/flow_entries/index.html.erb
<% if flash[:error] || flash[:info] %>
  <div class="shadow">
    <%= image_tag("alfred.png", class: "alfred", width: '100%') %>
  </div>
<% else %>
  <% if @private_mode %>
    <%= link_to 'Public modo', flow_entries_path(:id => @user.private_id) %>
  <% else %>
    <%= link_to 'Private modo', flow_entries_path(:id => @user.private_id, "private_mode" => "true") %>
  <% end %>
  <% @flow_entries_by_day.each do |flow_entries_of_day| %>
    <h2 class="ui header"><%= flow_entries_of_day[0].to_formatted_s(:rfc822) %></h2>
    <table class="ui celled table">
      <thead>
        <tr>
          <th>Date</th>
          <th>Activité</th>
          <th>Etat theorique (defi/competences)</th>
          <th>Potentiel de flow (moy ressentis)</th>
          <th>Categorie</th>
          <th>Niveau de compétences</th>
          <th>Niveau de défi</th>
          <th>Compétent</th>
          <th>Absorbé</th>
          <th>Objectifs clairs</th>
          <th>Controle</th>
          <th>Libre de l'ego</th>
          <th>Libre du temps</th>
          <th>Conditions réussite/échec claires</th>
          <th>Expérience enrichissante</th>
          <th>De mon initiative</th>
          <th>Niveau energie</th>
          <th>Niveau de bonheur</th>
          <th>Ambiance sociale</th>
        </tr>
      </thead>
      <tbody>
        <% flow_entries_of_day[1].each do |flow_entry| %>
        	<tr style="color: #424242">
    				<td><%= flow_entry.created_at.to_formatted_s(:short)  %></td>
    				<td class="<%= @private_mode ? "blurred" : "" %>"><%= flow_entry.activity_name %></td>
    				<td style="background-color: <%= bg_for_state(flow_entry.theorical_state) %>"><%= flow_entry.theorical_state %></td>
            <td><%= flow_entry.flow_potential/10 %> / 10</td>
            <td><%= flow_entry.activity_category %></td>
    				<td style="background-color: <%= bg_for_feelings(flow_entry.skill_level + 1) %>"><%= flow_entry.skill_level + 1 %> / 5</td>
    				<td style="background-color: <%= bg_for_feelings(flow_entry.challenge_level + 1) %>"><%= flow_entry.challenge_level + 1 %> / 5</td>
    				<td style="background-color: <%= bg_for_feelings(flow_entry.feeling_competent) %>"><%= flow_entry.feeling_competent %> / 5</td>
    				<td style="background-color: <%= bg_for_feelings(flow_entry.mentally_absorbed) %>"><%= flow_entry.mentally_absorbed %> / 5</td>
    				<td style="background-color: <%= bg_for_feelings(flow_entry.clear_objectives) %>"><%= flow_entry.clear_objectives %> / 5</td>
    				<td style="background-color: <%= bg_for_feelings(flow_entry.control_situation) %>"><%= flow_entry.control_situation %> / 5</td>
    				<td style="background-color: <%= bg_for_feelings(flow_entry.free_from_ego) %>"><%= flow_entry.free_from_ego %> / 5</td>
    				<td style="background-color: <%= bg_for_feelings(flow_entry.free_from_time) %>"><%= flow_entry.free_from_time %> / 5</td>
    				<td style="background-color: <%= bg_for_feelings(flow_entry.clear_conditions) %>"><%= flow_entry.clear_conditions %> / 5</td>
    				<td style="background-color: <%= bg_for_feelings(flow_entry.great_experience) %>"><%= flow_entry.great_experience %> / 5</td>
    				<td style="background-color: <%= bg_for_bool(flow_entry.is_voluntary?) %>"><%= flow_entry.is_voluntary? ? "Oui" : "Non" %></td>
            <td style="background-color: <%= bg_for_feelings_ten(flow_entry.energy) %>"><%= flow_entry.energy %> <%= " / 10" if flow_entry.energy %></td>
    				<td style="background-color: <%= bg_for_feelings_ten(flow_entry.happiness) %>"><%= flow_entry.happiness %>  <%= " / 10" if flow_entry.happiness %></td>
    				<td style="background-color: <%= bg_for_feelings(flow_entry.social) %>"><%= flow_entry.social %> <%= " / 5" if flow_entry.social %></td>
    			</tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="ui <%= key %> message">
    <p>
      <%= value.html_safe %>
    </p>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alfred</title>
    <%= csrf_meta_tags %>

    <%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type => "image/x-icon" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/no_container.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alfred</title>
    <%= csrf_meta_tags %>

    <%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type => "image/x-icon" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/drip_thx.html.erb
<div class="ui container">

  <h1>Merci</h1>

  <p>
    Ton clic sur le lien a bien provoqué l'action qu'il devait provoqué !
  </p>

  <p>
    Tu peux maintenant quitter la page :)
  </p>

</div>

app/views/pages/index.html.erb
<div class="ui container">

  <h1>Alfred le flow tracker</h1>

  <p>
    Bienvenue sur l'interface d'Alfred.
  </p>

  <p>
    Je te rappelle brievement l'objectif de l'app : analyser ton quotidien pour te permettre d'améliorer/changer ce que tu souhaiterais changer.
  </p>

  <h2 class="ui dividing header">Conseils d'utilisation (a lire)</h3>
  <p>
    Je te conseille de recueillir des données pendant une période d'au moins une semaine avant d'essayer de les interpréter.
  </p>
  <p>Lance Alfred tous les matins quand tu te leves et arrete le quand tu vas te coucher.</p>
  <p style="color: red">
    Pour interpréter les résultats je t'invite vivement a lire le chapitre 11 et 12 <a href="https://www.hacking-social.com/wp-content/uploads/2019/01/La-piste-du-flow-0.2.pdf">du livre de hacking-social.com</a>, ça te donnera toute les clés.
  </p>

  <h2 class="ui dividing header">Passer le test</h3>
  <p>
    Pense simplement a envoyer ces messages a alfred sur une durée d'au moins 2 jours :
  </p>
  <div class="ui bulleted list">
    <div class="item"><b>Start</b> : Alfred commencera a t'envoyer le questionnaire toute les 1-3h</div>
    <div class="item"><b>Stop</b> : Alfred arretera de t'envoyer le questionnaire</div>
  </div>

  <p>
    Ces deux commandes te permettent de passer correctement le test.
  </p>

  <h2 class="ui dividing header">Voir les résultats </h3>
  <p>
     Envoie <b>link</b> a Alfred, il te donnera le lien pour aller voir les résultats.<br>
     Ps : tu ne peux voir les résultats que si tu as assez de données.
  </p>

  <h2 class="ui dividing header">Bug report</h3>
  <p>
     Tu viens de remarquer un bug ? <br>
     Tu peux m'envoyer un mail a harry.jmg@gmail.com en mettant dans l'objet du mail <b>"[BUG ALFRED]"</b>
  </p>

  <h2 class="ui dividing header">En savoir plus sur le flow</h3>
  <p>
    Si tu n'es pas familier avec le concept de flow ou que tu ne comprends pas comment le test pourrait t'etre utile, je pense que c'est important que tu te renseigne un minimum, voici quelques ressources :
  </p>
  <div class="ui bulleted list">
    <div class="item"><a href="https://en.wikipedia.org/wiki/Flow_(psychology)">L'article wikipedia sur le flow</a></div>
    <div class="item"><a href="https://www.hacking-social.com/2018/09/03/fl1-donner-des-sens-a-la-vie-la-piste-du-flow/">Un article</a> et <a href="https://www.hacking-social.com/wp-content/uploads/2019/01/La-piste-du-flow-0.2.pdf">un livre génial intitulé "la piste du flow"</a> de hacking-social.com</div>
  </div>
  <p>
    Si tu as la flemme de lire, tape "flow psychologie" sur youtube et de regarde une ou deux vidéos sur le sujet.
  </p>

</div>

<style>
  p {
    font-size: medium;
  }

  .item {
    font-size: medium;
  }
</style>

app/views/users/index.html.erb
<div class="ui statistics">

  <div class="red statistic">
    <div class="value">
      <%= @users.all.count %>
    </div>
    <div class="label">
      Total users
    </div>
  </div>

  <div class="green statistic">
    <div class="value">
      <%= FlowEntry.all.count %>
    </div>
    <div class="label">
      Flow entries
    </div>
  </div>

</div>